name: Verify

on:
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Clone upstream
        run: ./cloneUpstream.sh

      - name: Remove Phone Home
        run: ./removePhoneHome.sh